// Simple Express.js backend for virtual try-on functionality
// This can be integrated into your existing USC test app

import express from 'express';
import multer from 'multer';
import fs from 'fs';
import path from 'path';
import cors from 'cors';

const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.static('public'));

// Configure multer for file uploads
const upload = multer({
  dest: 'uploads/',
  limits: { fileSize: 10 * 1024 * 1024 }, // 10MB limit
  fileFilter: (req, file, cb) => {
    if (file.mimetype.startsWith('image/')) {
      cb(null, true);
    } else {
      cb(new Error('Only image files are allowed'), false);
    }
  }
});

// In-memory storage for demo purposes
let products = [
  // Dresses
  { id: 1, name: 'Floral Summer Dress', price: '$89.99', category: 'dress', imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300' },
  { id: 2, name: 'Elegant Evening Dress', price: '$159.00', category: 'dress', imageUrl: 'https://images.unsplash.com/photo-1566479179817-c4c0dedd4cec?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300' },
  { id: 3, name: 'Casual Midi Dress', price: '$69.99', category: 'dress', imageUrl: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300' },
  
  // Shirts
  { id: 4, name: 'Classic White Shirt', price: '$49.99', category: 'shirt', imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300' },
  { id: 5, name: 'Denim Button-Up', price: '$59.00', category: 'shirt', imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300' },
  { id: 6, name: 'Silk Blouse', price: '$79.99', category: 'shirt', imageUrl: 'https://images.unsplash.com/photo-1564557287817-3785e38ec1f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300' },
  
  // Jeans
  { id: 7, name: 'High-Waist Skinny Jeans', price: '$89.99', category: 'jeans', imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300' },
  { id: 8, name: 'Relaxed Fit Jeans', price: '$75.00', category: 'jeans', imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300' },
  { id: 9, name: 'Distressed Boyfriend Jeans', price: '$95.99', category: 'jeans', imageUrl: 'https://images.unsplash.com/photo-1551513342-5b0f8cbdcf40?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300' },
  
  // Coats
  { id: 10, name: 'Mango Textured Coat', price: '$129.99', category: 'coat', imageUrl: 'https://assets.api.uizard.io/api/cdn/stream/1bd902b0-209c-4d5f-8e63-99d55c9016ba.png' },
  { id: 11, name: 'Zara Double breasted Coat', price: '$199.00', category: 'coat', imageUrl: 'https://assets.api.uizard.io/api/cdn/stream/fecff665-0ba6-4922-888b-84d485e1e917.png' },
  { id: 12, name: 'H&M Wool-blend Coat', price: '$99.99', category: 'coat', imageUrl: 'https://assets.api.uizard.io/api/cdn/stream/d20da14a-9c71-4b23-9104-66542fb7ab2b.png' },
];

let tryOnSessions = [];

// API Routes

// Get products by category
app.get('/api/products', (req, res) => {
  const { category } = req.query;
  
  if (category) {
    const filteredProducts = products.filter(p => p.category === category);
    res.json(filteredProducts);
  } else {
    res.json(products);
  }
});

// Virtual try-on upload endpoint
app.post('/api/try-on/upload', upload.single('photo'), (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ message: 'No image file provided' });
    }

    const { productId } = req.body;
    const product = products.find(p => p.id == productId);
    
    if (!product) {
      return res.status(404).json({ message: 'Product not found' });
    }

    // Simulate AI processing delay
    setTimeout(() => {
      const tryOnSession = {
        id: Date.now().toString(),
        productId: productId,
        userPhotoUrl: `/uploads/${req.file.filename}`,
        // Demo result images - in a real app, these would be generated by AI
        resultUrls: [
          'https://images.unsplash.com/photo-1566479179817-c4c0dedd4cec?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
          'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
          'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300'
        ],
        createdAt: new Date().toISOString()
      };

      tryOnSessions.push(tryOnSession);
      res.json(tryOnSession);
    }, 2000); // 2 second delay to simulate processing

  } catch (error) {
    console.error('Try-on upload error:', error);
    res.status(500).json({ message: 'Failed to process try-on request' });
  }
});

// Serve uploaded files
app.use('/uploads', express.static('uploads'));

// Create uploads directory if it doesn't exist
if (!fs.existsSync('uploads')) {
  fs.mkdirSync('uploads');
}

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'OK', timestamp: new Date().toISOString() });
});

// Error handling middleware
app.use((error, req, res, next) => {
  if (error instanceof multer.MulterError) {
    if (error.code === 'LIMIT_FILE_SIZE') {
      return res.status(400).json({ message: 'File too large' });
    }
  }
  
  console.error(error);
  res.status(500).json({ message: 'Something went wrong!' });
});

app.listen(PORT, () => {
  console.log(`Virtual Try-On API server running on port ${PORT}`);
  console.log(`Health check: http://localhost:${PORT}/health`);
});

export default app;